[workspace]
resolver = "3"
members = [
    "arch/aarch64",
    "arch/aarch64-paging",
    "arch/common",
    "collections",
    "drivers/common-aarch64",
    "drivers/common",
    "interrupts",
    "kernel",
    "fdt",
    "io",
    "log",
    "memory",
    "util",
    "xtask",
    "drivers/aarch64/generic/pl011_uart",
    "drivers/aarch64/qcom/uart_dm",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = true
opt-level = 2
