[package]
name = "drivers-aarch64"
version.workspace = true
edition.workspace = true

[dependencies]
io = { workspace = true }
drivers-common = { workspace = true }
drivers-common-aarch64 = { workspace = true }
klog = { workspace = true }
util = { workspace = true }
spin = { workspace = true }

[lints]
workspace = true
