[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
rustflags = [
    "-C", "link-arg=-T./arch/aarch64/linker/aarch64.ld",
    "-C", "link-arg=--gc-sections",
    "-C", "link-arg=--build-id=none",
]
linker = "rust-lld"
