cargo-features = ["per-package-target"]

[package]
name = "runtime"
version.workspace = true
edition.workspace = true
publish.workspace = true
forced-target = "aarch64-unknown-none"

[lib]
test = false
bench = false
doctest = false

[dependencies]
ipc = { workspace = true }
syscall = { workspace = true }

[lints]
workspace = true
