[package]
name = "arch-aarch64"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "kernel-aarch64"
path = "src/start.rs"
test = false

[features]
default = []
qemu-tests = [
    "kernel/qemu-tests",
    "dep:qemu-test-harness",
    "dep:qemu-test-harness-aarch64",
]

[dependencies]
aarch64-paging = { workspace = true }
arch-common = { workspace = true }
drivers-common-aarch64 = { workspace = true }
drivers-common = { workspace = true }
drivers-aarch64 = { workspace = true }
kernel = { workspace = true }
memory = { workspace = true }
collections = { workspace = true }
fdt = { workspace = true }
io = { workspace = true }
klog = { workspace = true }
qemu-test-harness = { workspace = true, optional = true }
qemu-test-harness-aarch64 = { workspace = true, optional = true }

[build-dependencies]
serde = { workspace = true }
serde_yaml = { workspace = true }

[lints]
workspace = true
