[package]
name = "arch-aarch64"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kernel-aarch64"
path = "src/start.rs"
test = false

[dependencies]
aarch64-paging = { path = "../aarch64-paging" }
kernel-core = { path = "../../core" }
memory = { path = "../../memory" }
util = { path = "../../util" }
spin = "0.10.0"

[features]
qemu_virt = []