[package]
name = "arch-aarch64"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kernel-aarch64"
path = "src/start.rs"
test = false

[dependencies]
aarch64-paging = { path = "../aarch64-paging" }
kernel-core = { path = "../../core" }
memory = { path = "../../memory" }
util = { path = "../../util" }
fdt = { path = "../../fdt" }
heapless = "0.9.1"

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
